AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation Template for VPC Setup

Parameters:
  VpcCidrBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC

  SubnetCidrBlock1:
    Type: String
    Default: 10.0.1.0/24
    Description: CIDR block for the first subnet

  SubnetCidrBlock2:
    Type: String
    Default: 10.0.2.0/24
    Description: CIDR block for the second subnet

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref SubnetCidrBlock1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref SubnetCidrBlock2

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My security group
      VpcId: !Ref MyVPC

  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC

Outputs:
  VpcId:
    Value: !Ref MyVPC
    Description: ID of the created VPC

  PublicSubnetId1:
    Value: !Ref PublicSubnet1
    Description: ID of the first public subnet

  PublicSubnetId2:
    Value: !Ref PublicSubnet2
    Description: ID of the second public subnet
